### PR TITLE
An HTML configuration file generator

### PR DESCRIPTION
**Pull request by redr00t**
An HTML configuration file generator.
uses:
-HTML
-Bootstraps
-JavaScript

The only values that will be generated in the "config.yaml" file by default are "username" and "password" the rest will not be placed unless the user enters a specific value.

It is a single file, therefore it can be deployed using Github Pages, here is an example of the code working:
https://redr00t.github.io/EsportsHelper/config-maker.html

### CODE REVIEW

**Comment by Yudaotor** [comment]
path should remove "", or use \\ instand of \

**Comment by Yudaotor** [comment]
> path should remove "", or use double\ instand of \

**Comment by redr00t** [comment]
> path should remove "", or use double\ instand of \

like this?

imagen

**Comment by Yudaotor** [comment]
> > path should remove "", or use double\ instand of \
> 
> like this?
> 
> imagen

yep

**Comment by Yudaotor** [comment]
I've added some page language support, check it out!

**Pull request merged**
