### PR TITLE
Update README.EN.md file

### PR DESCRIPTION
**Pull request by st0nke**
Fixed some typos, cleaned the text a bit to increase readability. Also added a disclaimer.

### CODE REVIEW

**Comment by Yudaotor** [comment]
Thanks for your PR
LGTM
Would you mind translating the Chinese in the program into English?

**Comment by st0nke** [comment]
Yep, was planning to do so.

**Comment by Yudaotor** [comment]
> Yep, was planning to do so.

Cheers

**Comment by Yudaotor** [comment]
> I am currently working on it, but unsure how it should be implemented: via selecting language on startup, or just changing all notifications to EN. I guess the first method should be better, yet I am unable to implement it myself as it will quite change the original structure.

Maybe Add a language config in yaml and then do if else stuff is a good idea

**Comment by st0nke** [comment]
I was considering implementing gettext method with all print lines in a separate file, but sadly, my python skills are quite low for this (also because of the need of bypassing print(f), as it not natively supported). If you can implement gettext or if/else system, than I can provide translations; if translating it directly over Chinese, new updates will constantly cause merge errors in my fork.

**Comment by Yudaotor** [comment]
> I was considering gettext method with all print lines in a separate file, but sadly, my python skills are quite low for this (and for if/else system too, honestly speaking). Gettext system is hard to implement also because of the need of bypassing print(f), as it not natively supported. If you can implement gettext or if/else system, then I can provide translations; if translating it directly over Chinese, new updates will constantly cause merge errors in my fork and lead to maintaining two separate builds.

I finished the system in Utils class.You just need add english translation into the dict and config en_US, it will works.Looking foward to your PR

**Pull request merged**
