### PR TITLE
EN-translation, formatting, imports sorting and typo fix.

### PR DESCRIPTION
**Pull request by st0nke**
Added EN translations to Utils.py, adjusted overall formatting and imports, fixed README.EN.md a bit, changed ignoreBoardCast to ignoreBroadCast to fix typo.

### CODE REVIEW

**Comment by st0nke** [comment]
Btw I have errors when trying to launch both main branch and translated one:

```
name 'driver' is not defined
  File "C:\Users\st0nke\VS\EH_EN\EsportsHelper\Config.py", line 16, in __init__
    with open(configPath, "r", encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

  File "C:\Users\st0nke\VS\EH_EN\main.py", line 124, in <module>
    main()
  File "C:\Users\st0nke\VS\EH_EN\main.py", line 108, in main
    config = Config(log, args.configPath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\st0nke\VS\EH_EN\EsportsHelper\Config.py", line 48, in __init__
    input(_log("按任意键退出", lang=self.language))
                              ^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'language'

During handling of the above exception, another exception occurred:

  File "C:\Users\st0nke\VS\EH_EN\main.py", line 128, in <module>
    sysQuit(driver, format_exc())
            ^^^^^^
NameError: name 'driver' is not defined
```

**Comment by Yudaotor** [comment]
I think U disunderstanding me about i18n. translations should be put inside into the dict.like {"你好": "hello"}those numbers should be deleted

**Comment by st0nke** [comment]
Updated, is it correct now?

**Comment by Yudaotor** [comment]
> Updated, is it correct now?

LGTM

**Pull request merged**
